### ISSUE TITLE
Could you add rss support?

### ISSUE THREAD

**Issue by caizixian** [zhchbin/zhchbin.github.io#1]

**Comment by zhchbin** [comment]
Thanks for you concern. Currently plugin: [hexojs/hexo-generator-feed](https://github.com/hexojs/hexo-generator-feed) is _NOT_ compatible with hexo (`3.0.0-rc.4`) I'm using yet.

**Comment by zhchbin** [comment]
Added: http://zhchbin.github.io/atom.xml

**Comment by caizixian** [comment]
Finally. 😀
